# Generated by Django 5.1.4 on 2024-12-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessedImage',
            new_name='ProcessedTest',
        ),
    ]
